name: Check dead domains
run-name: Check dead domains
on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'
permissions:
  contents: write

jobs:
  get-files:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Get script
        run: |
          curl -sSL --retry 2 --retry-all-errors \
            "${{ vars.SCAM_BLOCKLIST_URL }}/scripts/check_dead.sh" \
            -o check_dead.sh

      - name: Push
        run: |
          git config user.email ${{ vars.GIT_EMAIL }}
          git config user.name ${{ vars.GIT_USERNAME }}
          git add .
          git diff-index --quiet HEAD || git commit -m "$(date +"%d-%m-%Y")"
          git push -q

  check-resurrected:
    needs: get-files
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Check for resurrected domains
        run: |
          curl -sSL --retry 2 --retry-all-errors \
            "${{ vars.SCAM_BLOCKLIST_URL }}/data/dead_domains.txt" \
            -o dead_domains.tmp

          bash check_dead.sh --check-alive dead_domains.tmp

      - name: Push
        run: |
          git config user.email ${{ vars.GIT_EMAIL }}
          git config user.name ${{ vars.GIT_USERNAME }}
          git add .
          git diff-index --quiet HEAD || git commit -m "$(date +"%d-%m-%Y")"
          git push -q

  check-dead-part-1:
    needs: check-resurrected
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Check for dead domains (part 1)
        run: |
          curl -sSL --retry 2 --retry-all-errors \
            "${{ vars.SCAM_BLOCKLIST_URL }}/data/raw.txt" \
            -o raw.tmp

          bash check_dead.sh --check-dead-part-1 raw.tmp

      - name: Push
        run: |
          git config user.email ${{ vars.GIT_EMAIL }}
          git config user.name ${{ vars.GIT_USERNAME }}
          git add .
          git diff-index --quiet HEAD || git commit -m "$(date +"%d-%m-%Y")"
          git push -q

  check-dead-part-2:
    needs: check-dead-part-1
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Check for dead domains (part 2)
        run: |
          curl -sSL --retry 2 --retry-all-errors \
            "${{ vars.SCAM_BLOCKLIST_URL }}/data/raw.txt" \
            -o raw.tmp

          bash check_dead.sh --check-dead-part-2 raw.tmp

      - name: Push
        run: |
          git config user.email ${{ vars.GIT_EMAIL }}
          git config user.name ${{ vars.GIT_USERNAME }}
          git add .
          git diff-index --quiet HEAD || git commit -m "$(TZ=Asia/Singapore date +"%d-%m-%Y")"
          git push -q
